services:
  mongodb:
    image: mongo:7
    container_name: issue-tracker-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: issue-tracker
    volumes:
      - issue-tracker-mongo:/data/db

volumes:
  issue-tracker-mongo:
